server:
  port: 8084
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-nodes: 47.106.37.207:9300
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ribbon:
  eureka:
    enabled: true